using System;
namespace Cyber.HabboHotel.Quests
{
	public enum QuestType
	{
		FURNI_MOVE,
		FURNI_ROTATE,
		FURNI_PLACE,
		FURNI_PICK,
		FURNI_SWITCH,
		FURNI_STACK,
		FURNI_DECORATION_FLOOR,
		FURNI_DECORATION_WALL,
		SOCIAL_VISIT,
		SOCIAL_CHAT,
		SOCIAL_FRIEND,
		SOCIAL_RESPECT,
		SOCIAL_DANCE,
		SOCIAL_WAVE,
		PROFILE_CHANGE_LOOK,
		PROFILE_CHANGE_MOTTO,
		PROFILE_BADGE,
		EXPLORE_FIND_ITEM,
		SUMMER_ENTER_ROOM,
		ADD_FRIENDS,
		WAVE_USERS,
		KISS_USERS,
		WEAR_HAT,
		MASS_DANCE,
		GIFT_OTHERS,
		STAND_ON,
		GIVE_ITEM,
		GIVE_COFFEE,
		WAVE_REINDEER,
		XMAS_PARTY
	}
}
